baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde"

DefaultContentLanguage = "en"
copyright = "Everything is mine"

[languages]
  [languages.en]
    title = "My blog"
    weight = 1
  [languages.fr]
    copyright = "Tout est à moi"
    title = "Mon blog"
    weight = 2
